-- ALTER TABLE batch
--     ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
--     ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;-- DEFAULT CURRENT_TIMESTAMP;


ALTER TABLE batch
ALTER COLUMN updated_at
SET DEFAULT CURRENT_TIMESTAMP
-- ALTER COLUMN updated_at DEFAULT CURRENT_TIMESTAMP
